name: playground
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - networkx>=3.1
  - matplotlib>=3.7.0
  - pyvista=0.39.0
  - pythonocc-core=7.7.2
  - pyqt
  - vtk=9.2.5
  - occt=7.7.2
  - pip
  - pip:
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=23.0.0
    - isort>=5.0.0
    - mypy>=1.0.0 